version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:5173" # Mapea el puerto interno 5173 al puerto 8080 en el host
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network: