version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:5173"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app # Mapea la carpeta del backend
      - /app/node_modules # Evita conflictos con node_modules
    networks:
      - app-network

networks:
  app-network: